---
{{- if .Values.multus.n2n3Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-net1
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.n2n3Interface.hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.n2n3Interface.IPadd "/" .Values.multus.n2n3Interface.Netmask | nospace | quote }}
                }
        ]
        {{- if .Values.multus.n2n3Interface.Gateway }}
        ,"routes": [
                {
                        "dst": "@ROUTE_GNB_TO_EXTCN@",
                        "gw": "@GW_GNB_TO_EXTCN@"
                }
        ]
        {{- end }}
      }
    }'
{{- end }}
---
{{- if .Values.multus.ru1Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-net2
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.ru1Interface.hostInterface | nospace | quote }},
      {{- if .Values.multus.ru1Interface.mtu }}
      "mtu": {{ .Values.multus.ru1Interface.mtu }},
      {{- end }}
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.ru1Interface.IPadd "/" .Values.multus.ru1Interface.Netmask | nospace | quote }}
                }
        ]
      }
    }'
{{- end }}
---
{{- if .Values.multus.ru2Interface.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-net3
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": {{- cat .Values.multus.ru2Interface.hostInterface | nospace | quote }},
      {{- if .Values.multus.ru2Interface.mtu }}
      "mtu": {{ .Values.multus.ru2Interface.mtu }},
      {{- end }}
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.ru2Interface.IPadd "/" .Values.multus.ru2Interface.Netmask | nospace | quote }}
                }
        ]
      }
    }'
{{- end }}
