---
{{- if .Values.multus.create }}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-net1
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": {{- cat .Values.multus.n2n3hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.n2n3IPadd "/" .Values.multus.n2n3Netmask | nospace | quote }}
                }
        ],
        "routes": [
                {
                        "dst": "@ROUTE_AMF_MULTUS@",
                        "gw": "@GW_AMF_MULTUS@"
                }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-net2
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": {{- cat .Values.multus.sfp1hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.sfp1IPadd "/" .Values.multus.sfp1Netmask | nospace | quote }}
                }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-net3
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": {{- cat .Values.multus.sfp2hostInterface | nospace | quote }},
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.sfp2IPadd "/" .Values.multus.sfp2Netmask | nospace | quote }}
                }
        ]
      }
    }'
{{- end }}
