apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-nr-ue.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oai-nr-ue.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-nr-ue.selectorLabels" . | nindent 8 }}
        app: 5grf-sim
      annotations:
    {{- if .Values.multus.create }}
        k8s.v1.cni.cncf.io/networks: >-
          [{
                 "name": "{{ .Chart.Name }}-net1"
          }]
    {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
      containers:
      - name: nr-ue
        image: "{{ .Values.nfimage.repository }}:{{ .Values.nfimage.version }}"
        {{- if .Values.resources.define}}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.limits.memory | quote }}
            cpu: {{ .Values.resources.limits.cpu | quote }}
        {{- end}}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- if .Values.start.nrue}}
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: timeZone
          - name: RFSIMULATOR
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: rfSimulator
          - name: FULL_IMSI
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: fullImsi
          - name: FULL_KEY
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: fullKey
          - name: OPC
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: opc
          - name: DNN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: dnn
          - name: NSSAI_SST
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nssaiSst
          - name: NSSAI_SD
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nssaiSd
          - name: USE_ADDITIONAL_OPTIONS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: useAdditionalOptions
      - name: tcpdump
        image: "{{ .Values.tcpdumpimage.repository }}:{{ .Values.tcpdumpimage.version }}"
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- if .Values.start.tcpdump}}
        command:
          - /bin/sh
          - -c
          - /usr/sbin/tcpdump -ni net1 src {{ .Values.multus.ipadd }} or dst {{ .Values.multus.ipadd }} -w /pcap/oai-nr-ue_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        {{- if .Values.persistent.sharedvolume}}
        volumeMounts:
        - mountPath: "/pcap"
          name: oai5g-pv
        {{- end}}
      volumes:
      {{- if .Values.persistent.sharedvolume}}
      - name: oai5g-pv
        persistentVolumeClaim:
          claimName: oai5g-pvc
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.nodeSelector}}
      nodeSelector: 
         {{- toYaml .Values.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if .Values.nodeName}}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
