- name: "n2"
  enabled: ${MULTUS_CU_N2}
  hostInterface: "${IF_NAME_CU_N2}"
  ipAdd: "${IP_CU_N2}"
  netmask: "${NETMASK_CU_N2}"
  defaultRoute: "${GW_CU_N2}"
  routes: "${ROUTES_CU_N2}"
  type: macvlan
  mode: "bridge"

- name: "f1"
  enabled: ${MULTUS_CU_F1}
  hostInterface: "${IF_NAME_CU_F1}"
  ipAdd: "${IP_CU_F1}"
  netmask: "${NETMASK_CU_F1}"
  defaultRoute: "${GW_CU_F1}"
  routes: "${ROUTES_CU_F1}"
  type: macvlan
  mode: "bridge"

- name: "n3"
  enabled: ${MULTUS_CU_N3}
  hostInterface: "${IF_NAME_CU_N3}"
  ipAdd: "${IP_CU_N3}"
  netmask: "${NETMASK_CU_N3}"
  defaultRoute: "${GW_CU_N3}"
  routes: "${ROUTES_CU_N3}"
  type: macvlan
  mode: "bridge"

- name: "e2"
  enabled: ${MULTUS_CU_E2}
  hostInterface: "${IF_NAME_CU_E2}"
  ipAdd: "${IP_CU_E2}"
  netmask: "${NETMASK_CU_E2}"
  type: macvlan
  mode: "bridge"
