- name: "f1c"
  enabled: ${MULTUS_DU_F1C}
  hostInterface: "${IF_NAME_DU_F1C}"
  ipAdd: "${IP_DU_F1C}"
  netmask: "${NETMASK_DU_F1C}"
  defaultRoute: "${GW_DU_F1C}"
  routes: "${ROUTES_DU_F1C}"
  type: macvlan
  mode: "bridge"

- name: "f1u"
  enabled: ${MULTUS_DU_F1U}
  hostInterface: "${IF_NAME_DU_F1U}"
  ipAdd: "${IP_DU_F1U}"
  netmask: "${NETMASK_DU_F1U}"
  defaultRoute: "${GW_DU_F1U}"
  routes: "${ROUTES_DU_F1U}"
  type: macvlan
  mode: "bridge"

- name: "e2"
  enabled: ${MULTUS_GNB_E2}
  hostInterface: "${IF_NAME_GNB_E2}"
  ipAdd: "${IP_GNB_E2}"
  netmask: "${NETMASK_GNB_E2}"
  type: macvlan
  mode: "bridge"

- name: "uplane1"
  enabled: true
  mac: "${MAC_UPLANE1}"
  type: sriov
  sriovNetworkNamespace: "sriov-network-operator"
  sriovResourceName: "ruvfiou"
  vlan: "${VLAN_RU}"

- name: "cplane1"
  enabled: true
  mac: "${MAC_CPLANE1}"
  type: sriov
  sriovNetworkNamespace: "sriov-network-operator"
  sriovResourceName: "ruvfioc"
  vlan: "${VLAN_RU}"
