#!/bin/bash

# Load 5G parameters generated by Ansible
if [ -f /etc/oai/5g-env.sh ]; then
    source /etc/oai/5g-env.sh
else
    echo "/etc/oai/5g-env.sh not found, using following default parameters:"
    MCC="001" 
    MNC="01" 
    TAC="1" 

    # DNN0 and DNN1 must be initialized in scripts demo-oai.py or in prepare-demo-oai.sh scripts 
    DNN0_PDU_TYPE="IPV4" # XXX "IPV4" or "IPV4V6" 
    DNN1_PDU_TYPE="IPV4" # XXX "IPV4" or "IPV4V6"

    # NSSAI (SST,SD) Configuration
    #
    # NOTA on SD format encoding in the charts
    # - in mysql database, SD field is a string/hexadecimal without 0x prefix,
    #    and encoded with the format: \"ABCDEF\"
    # - in gNB configmaps sd format should include 0x prexix or use the decimal form
    # - in core/config.yaml and ue/values.yaml, it is in hex form without 0x prefix

    # The case of empty SD field (encoded as "EMPTY" is particular, it will correspond to :
    # - \"FFFFFF\" in mysql database
    # - only sst field defined in nssai within config.yaml of the CN
    # - only sst field defined in gnb.conf
    # - "16777215" in nr-ue rfsim scenario
    #

    SLICE1_SST="1"
    SLICE1_SD="EMPTY" # can also be set to "EMPTY" 
    SLICE1_5QI="9" # non-GBR
    SLICE1_ARP_PRIORITY_LEVEL="8"
    SLICE1_ARP_PREEMPT_CAP="NOT_PREEMPT" # "NOT_PREEMPT" or "MAY_PREEMPT" 
    SLICE1_ARP_PREEMPT_VULN="PREEMPTABLE" # "PREEMPTABLE" or "NOT_PREEMPT" 
    SLICE1_PRIORITY_LEVEL="1"
    SLICE1_UPLINK="20Mbps"
    SLICE1_DOWNLINK="40Mbps"
    SLICE1_IP_PREFIX="12.1.1"

    SLICE2_SST="1"
    SLICE2_SD="000001"
    SLICE2_5QI="5" # non-GBR
    SLICE2_ARP_PRIORITY_LEVEL="1"
    SLICE2_ARP_PREEMPT_CAP="NOT_PREEMPT" # "NOT_PREEMPT" or "MAY_PREEMPT"
    SLICE2_ARP_PREEMPT_VULN="PREEMPTABLE" # "PREEMPTABLE" or "NOT_PREEMPT"
    SLICE2_PRIORITY_LEVEL="1"
    SLICE2_UPLINK="100Mbps"
    SLICE2_DOWNLINK="200Mbps"
    SLICE2_IP_PREFIX="14.1.1"

    FULL_KEY="fec86ba6eb707ed08905757b1bb44b8f" 
    OPC="C42449363BBAD02B66D16BC975D77CC1" 
    RFSIM_IMSI="001010000001121"
    RFSIM_IMSI_UE2="001010000001122"
    RFSIM_IMSI_UE3="001010000001123"

    # Dynamic mapping for UEs → slice index (1 for SLICE1 or 2 for SLICE2)

    UE_SLICE_MAP=(
      "0000000001:2"
      "0000000002:1"
      "0000000003:1"
      "0000000004:1"
      "0000000005:1"
      "0000000006:1"
      "0000000007:2"
      "0000000008:1"
      "0000000009:1"
      "0000000010:1"
      "0000000011:1"
      "0000000012:1"
      "0000000013:1"
      "0000000014:1"
      "${RFSIM_IMSI:5}:1"
      "${RFSIM_IMSI_UE2:5}:1"
      "${RFSIM_IMSI_UE3:5}:1"
    )
fi

# IP suffix is incremented by 1 for each UE, starting from $START_IP
GNB_ID="0xe020"
START_IP=11

##########################################################################################
TMP="/tmp/tmp.$USER"
mkdir -p "$TMP"

function update() {
    NS=$1; shift
    NODE_AMF_UPF=$1; shift
    NODE_GNB=$1; shift
    RRU=$1; shift 
    RUN_MODE=$1; shift # in ["full", "gnb-only", "gnb-upf"]
    LOGS=$1; shift # boolean in [true, false]
    PCAP=$1; shift # boolean in [true, false]
    MONITORING=$1; shift # boolean in [true, false]
    FLEXRIC=$1; shift # boolean
    LOCAL_CORE_INTERFACE=$1; shift
    LOCAL_RAN_INTERFACE=$1; shift
    PREFIX_DEMO=$1; shift
    CN_MODE=$1; shift
    GNB_MODE=$1; shift
    DNN0=$1; shift
    DNN1=$1; shift
    REGCRED_NAME=$1; shift
    REGCRED_PWD=$1; shift
    REGCRED_EMAIL=$1; shift

    # Convert to lowercase boolean parameters
    GNB_ONLY="${GNB_ONLY,,}"
    LOGS="${LOGS,,}"
    PCAP="${PCAP,,}"
    MONITORING="${MONITORING,,}"
    FLEXRIC="${FLEXRIC,,}"

    # if node is a sopnode-w or sopnode-l1, add the "-v30" suffix
    if [[ "$NODE_AMF_UPF" == "sopnode-l1" || "$NODE_AMF_UPF" == "sopnode-w1" ]]; then
	NODE_AMF_UPF="${NODE_AMF_UPF}-v30"
    fi
    if [[ $NODE_GNB == "sopnode-l1" || "$NODE_GNB" == "sopnode-w1" ]]; then
	NODE_GNB="${NODE_GNB}-v30"
    fi
    
    if [[ "$CN_MODE" = "advance" ]]; then
	mode="advance"
	MODE="ADVANCE"
    else
	mode="basic"
	MODE="BASIC"
    fi
    
    echo "Configuring demo-oai.sh script"
    cat > "$TMP"/demo-oai.sed <<EOF
s|@DEF_NS@|$NS|
s|@DEF_NODE_AMF_UPF@|$NODE_AMF_UPF|
s|@DEF_NODE_GNB@|$NODE_GNB|
s|@DEF_RRU@|$RRU|
s|@DEF_RUN_MODE@|$RUN_MODE|
s|@DEF_GNB_MODE@|$GNB_MODE|
s|@DEF_LOGS@|$LOGS|
s|@DEF_PCAP@|$PCAP|
s|@DEF_MONITORING@|$MONITORING|
s|@DEF_FLEXRIC@|$FLEXRIC|
s|@DEF_LOCAL_CORE_INTERFACE@|$LOCAL_CORE_INTERFACE|
s|@DEF_LOCAL_RAN_INTERFACE@|$LOCAL_RAN_INTERFACE|
s|@DEF_MCC@|${MCC}|g
s|@DEF_MNC@|${MNC}|g
s|@DEF_TAC@|${TAC}|g
s|@DEF_DNN0@|${DNN0}|
s|@DEF_DNN0_PDU_TYPE@|${DNN0_PDU_TYPE}|
s|@DEF_DNN1@|${DNN1}|
s|@DEF_DNN1_PDU_TYPE@|${DNN1_PDU_TYPE}|
s|@DEF_SLICE1_SST@|${SLICE1_SST}|
s|@DEF_SLICE1_SD@|${SLICE1_SD}|
s|@DEF_SLICE1_5QI@|${SLICE1_5QI}|
s|@DEF_SLICE1_ARP_PRIORITY_LEVEL@|${SLICE1_ARP_PRIORITY_LEVEL}|
s|@DEF_SLICE1_ARP_PREEMPT_CAP@|${SLICE1_ARP_PREEMPT_CAP}|
s|@DEF_SLICE1_ARP_PREEMPT_VULN@|${SLICE1_ARP_PREEMPT_VULN}|
s|@DEF_SLICE1_PRIORITY_LEVEL@|${SLICE1_PRIORITY_LEVEL}|
s|@DEF_SLICE1_UPLINK@|${SLICE1_UPLINK}|
s|@DEF_SLICE1_DOWNLINK@|${SLICE1_DOWNLINK}|
s|@DEF_SLICE2_SST@|${SLICE2_SST}|
s|@DEF_SLICE2_SD@|${SLICE2_SD}|
s|@DEF_SLICE2_5QI@|${SLICE2_5QI}|
s|@DEF_SLICE2_ARP_PRIORITY_LEVEL@|${SLICE2_ARP_PRIORITY_LEVEL}|
s|@DEF_SLICE2_ARP_PREEMPT_CAP@|${SLICE2_ARP_PREEMPT_CAP}|
s|@DEF_SLICE2_ARP_PREEMPT_VULN@|${SLICE2_ARP_PREEMPT_VULN}|
s|@DEF_SLICE2_PRIORITY_LEVEL@|${SLICE2_PRIORITY_LEVEL}|
s|@DEF_SLICE2_UPLINK@|${SLICE2_UPLINK}|
s|@DEF_SLICE2_DOWNLINK@|${SLICE2_DOWNLINK}|
s|@DEF_GNB_ID@|${GNB_ID}|
s|@DEF_FULL_KEY@|${FULL_KEY}|g
s|@DEF_OPC@|${OPC}|g
s|@DEF_RFSIM_IMSI@|${RFSIM_IMSI}|g
s|@DEF_RFSIM_IMSI_UE2@|${RFSIM_IMSI_UE2}|g
s|@DEF_RFSIM_IMSI_UE3@|${RFSIM_IMSI_UE3}|g
s|@DEF_PREFIX_DEMO@|$PREFIX_DEMO|
s|@MODE@|$MODE|g
s|@mode@|$mode|g
s|@DEF_REGCRED_NAME@|$REGCRED_NAME|
s|@DEF_REGCRED_PWD@|$REGCRED_PWD|
s|@DEF_REGCRED_EMAIL@|$REGCRED_EMAIL|
EOF

    cp "$PREFIX_DEMO"/demo-oai.sh "$TMP"/demo-oai-orig.sh
    echo "Configuring demo-oai.sh script with possible new R2lab FIT nodes and registry credentials"
    sed -f "$TMP"/demo-oai.sed < "$TMP"/demo-oai-orig.sh > "$PREFIX_DEMO"/demo-oai.sh
    diff "$TMP"/demo-oai-orig.sh "$PREFIX_DEMO"/demo-oai.sh

    echo "Generating SQL database with dynamic parameters..."

    generate_dynamic_sql "$PREFIX_DEMO" "$DNN0" "$DNN1" "$MCC" "$MNC" "$FULL_KEY" "$OPC"
}

# Dynamic SQL generation 

generate_dynamic_sql() {
    PREFIX_DEMO="$1"
    DEF_DNN0="$2"
    DEF_DNN1="$3"
    DEF_MCC="$4"
    DEF_MNC="$5"
    DEF_FULL_KEY="$6"
    DEF_OPC="$7"

    DB="$PREFIX_DEMO/oai5g-rru/patch-mysql/oai_db-basic.sql"
    cp "$DB" "$DB".orig
    AS_DB=${TMP}/TableAS.sql
    SMSD_DB=${TMP}/TableSMSD.sql
    rm -f "$AS_DB" "$SMSD_DB"
    touch "$AS_DB" "$SMSD_DB"
    echo "Generating new database at $DB"

    # 1) Copy static top of file (tables definitions unchanged)
    cat "$PREFIX_DEMO/oai5g-rru/patch-mysql/oai_db-basic-template-head.sql" > "$DB"

    IP=$START_IP

    echo "## ue_slice_map: ${UE_SLICE_MAP[@]}"

    for entry in "${UE_SLICE_MAP[@]}"; do
        UE=${entry%%:*}
        SLICE=${entry##*:}
        IMSI="${DEF_MCC}${DEF_MNC}${UE}"

	echo "## UE $UE: SLICE: ${entry##*:}, IMSI:${DEF_MCC}${DEF_MNC}${UE} "

        # Slice parameters selection
        if [[ "$SLICE" == "1" ]]; then
	    DNN=${DEF_DNN0}
	    DNN_PDU_TYPE=${DNN0_PDU_TYPE}
            SST=${SLICE1_SST}
            SD=${SLICE1_SD}
            QOS_5QI=${SLICE1_5QI}
            ARP_PRIORITY_LEVEL=${SLICE1_ARP_PRIORITY_LEVEL}
	    ARP_PREEMPT_CAP=${SLICE1_ARP_PREEMPT_CAP}
	    ARP_PREEMPT_VULN=${SLICE1_ARP_PREEMPT_VULN}
	    PRIORITY_LEVEL=${SLICE1_PRIORITY_LEVEL}
	    UPLINK=${SLICE1_UPLINK}
	    DOWNLINK=${SLICE1_DOWNLINK}
            IP_PREFIX=${SLICE1_IP_PREFIX}
        else
	    DNN=${DEF_DNN1}
	    DNN_PDU_TYPE=${DNN1_PDU_TYPE}
            SST=${SLICE2_SST}
            SD=${SLICE2_SD}
            QOS_5QI=${SLICE2_5QI}
            ARP_PRIORITY_LEVEL=${SLICE2_ARP_PRIORITY_LEVEL}
	    ARP_PREEMPT_CAP=${SLICE2_ARP_PREEMPT_CAP}
	    ARP_PREEMPT_VULN=${SLICE2_ARP_PREEMPT_VULN}
	    PRIORITY_LEVEL=${SLICE2_PRIORITY_LEVEL}
	    UPLINK=${SLICE2_UPLINK}
	    DOWNLINK=${SLICE2_DOWNLINK}
            IP_PREFIX=${SLICE2_IP_PREFIX}
        fi

        IPADDR="${IP_PREFIX}.${IP}"
        ((IP++))

        # AuthenticationSubscription
        cat >> "$AS_DB" <<EOF
INSERT INTO \`AuthenticationSubscription\` (\`ueid\`, \`authenticationMethod\`, \`encPermanentKey\`, \`protectionParameterId\`, \`sequenceNumber\`, \`authenticationManagementField\`, \`algorithmId\`, \`encOpcKey\`, \`encTopcKey\`, \`vectorGenerationInHss\`, \`n5gcAuthMethod\`, \`rgAuthenticationInd\`, \`supi\`) VALUES
('${IMSI}', '5G_AKA', '${DEF_FULL_KEY}', '${DEF_FULL_KEY}', '{\"sqn\": \"000000000020\", \"sqnScheme\": \"NON_TIME_BASED\", \"lastIndexes\": {\"ausf\": 0}}', '8000', 'milenage', '${DEF_OPC}', NULL, NULL, NULL, NULL, '${IMSI}');
EOF

        # SessionManagementSubscriptionData
        cat >> "$SMSD_DB" <<EOF
INSERT INTO \`SessionManagementSubscriptionData\` (\`ueid\`, \`servingPlmnid\`, \`singleNssai\`, \`dnnConfigurations\`) VALUES
('${IMSI}', '${DEF_MCC}${DEF_MNC}', '{\"sst\": ${SST}, \"sd\": \"${SD}\"}','{\"${DNN}\":{\"pduSessionTypes\":{ \"defaultSessionType\": \"${DNN_PDU_TYPE}\"},\"sscModes\": {\"defaultSscMode\": \"SSC_MODE_1\"},\"5gQosProfile\": {\"5qi\": ${QOS_5QI},\"arp\":{\"priorityLevel\": ${ARP_PRIORITY_LEVEL},\"preemptCap\": \"${ARP_PREEMPT_CAP}\",\"preemptVuln\":\"${ARP_PREEMPT_VULN}\"},\"priorityLevel\":${PRIORITY_LEVEL}},\"sessionAmbr\":{\"uplink\":\"${UPLINK}\", \"downlink\":\"${DOWNLINK}\"},\"staticIpAddress\":[{\"ipv4Addr\": \"${IPADDR}\"}]}}');
EOF
    done

    {
	# append AuthenticationSubscription Table
	cat "$AS_DB"

	# append in-between empty tables
	cat "$PREFIX_DEMO/oai5g-rru/patch-mysql/oai_db-basic-template-between.sql"

	# append SessionManagementSubscriptionData Table
	cat "$SMSD_DB"

	# append tail of DB (indexes, commit)
	cat "$PREFIX_DEMO/oai5g-rru/patch-mysql/oai_db-basic-template-tail.sql"
    }   >> "$DB"
    echo "cat file  >>>>>>"
    cat "$DB"
}


if test $# -ne 20; then
    echo "USAGE: configure-demo-oai.sh namespace node_amf_upf node_gnb rru gnb_only logs pcap monitoring flexric local_core_interface local_ran_interface prefix_demo cn_mode gnb_mode DNN0 DNN1 regcred_name regcred_password regcred_email "
    exit 1
else
    shift
    printf 'Running update with inputs: %s\n' "$@"
    update "$@"
    exit 0
fi
