#!/bin/bash

# This script aims to configure Quectel RM500Q-GL UE devices and make them ready to attach to 4G/5G networks
# default DNN is "oai.ipv4"
# no DNN2 and no NSSAI defined by default
# default mode is mbim

COMMAND=$(basename $0)
function usage() {
    echo "USAGE: $COMMAND --dnn=oai --dnn2=oai2 --nssai=01.012345 --nssai2=01.012345 --mode=mbim|qmi"
    exit 2
}

die() { echo "$*" >&2; usage; }  # complain to STDERR and exit with error
needs_arg() { if [ -z "$OPTARG" ]; then die "No arg for --$OPT option"; fi; }

# Default configuration
DEF_DNN="oai.ipv4"; DNN="$DEF_DNN"
DEF_DNN2=""; DNN2="$DEF_DNN2"
DEF_NSSAI=""; NSSAI="$DEF_NSSAI"
DEF_NSSAI2=""; NSSAI2="$DEF_NSSAI2"
DEF_MODE="mbim"; MODE="$DEF_MODE" # mbim|qmi

while getopts "h-:" OPT; do
  # support long options: https://stackoverflow.com/a/28466267/519360
  if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
    OPT="${OPTARG%%=*}"       # extract long option name
    OPTARG="${OPTARG#"$OPT"}" # extract long option argument (may be empty)
    OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
  fi
  case "$OPT" in
    dnn )    needs_arg; DNN="$OPTARG" ;;
    dnn2 )   needs_arg; DNN2="$OPTARG" ;;
    nssai )  needs_arg; NSSAI="$OPTARG" ;;
    nssai2 ) needs_arg; NSSAI2="$OPTARG" ;;
    mode )   needs_arg; MODE="$OPTARG" ;;
    \? )     usage ;;  # bad short option (error reported via getopts)
    * )      die "Illegal option --$OPT" ;;            # bad long option
  esac
done
shift $((OPTIND-1)) # remove parsed options and args from $@ list

echo "Running prepare with DNN=$DNN, DNN2=$DNN2, NSSAI=$NSSAI, NSSAI2=$NSSAI2 and MODE=$MODE"

uoff
sleep 2
uon
sleep 25
config-ue --dnn "$DNN" --dnn2 "$DNN2" --nssai "$NSSAI" --nssai2 "$NSSAI2" --mode "$MODE"
sleep 5
check-ue2
init.sh
