apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: {{ .Chart.Name }}-script
data:
   {{ (.Files.Glob "conf/mounted.conf").AsConfig | indent 2 | trim }}
