apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ran5g-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: ran5g-pv